import Head from "next/head";
import { Banner, Tabs } from "@/components";
import { useState, useEffect } from "react";

export default function Home({ apiKey }) {
  const [recipess, setRecipess] = useState([]);
  const [foodType, setFoodType] = useState("");

  useEffect(() => {
    const fetchData = async () => {
      const response = await fetch(
        `https://api.spoonacular.com/recipes/complexSearch?apiKey=${apiKey}&query=${foodType}`
      );

      const data = await response.json();
      setRecipess(data.results);
    };

    fetchData();
  }, [apiKey, foodType]);

  console.log(recipess, "pp");

  return (
    <>
      <Head>
        <title>Foodpals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/tab-logo.svg" />
      </Head>
      <main style={{ width: "calc(100% - 85px)", marginLeft: "auto" }}>
        <Banner />
        <Tabs setFoodType={setFoodType} />

        {Array.isArray(recipess)
          ? recipess.map((n) => {
              return <p key={n.id}>{n.title}</p>;
            })
          : null}
      </main>
    </>
  );
}

//Fetch api

// const getStaticProps = async () => {
//   const res = await fetch(
//     `${process.env.NEXT_APP_SEARCH_QUERY}{foodtype}&number=20&apiKey=${process.env.NEXT_APP_API_KEY}`
//   );
//   const recipes = await res.json();

//   return {
//     props: {
//       recipes,
//     },
//   };
// };

export const getServerSideProps = async () => {
  return {
    props: {
      apiKey: process.env.NEXT_APP_API_KEY,
    },
  };
};
